baseURL = "https://zozores.netlify.app"
theme = "hugo-coder"
languageCode = "pt-br"
defaultContentLanguage = "pt-br"
paginate = 6
enableEmoji = true

# [services]
# [services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"

[markup.highlight]
noClasses = false

[params]
author = "Thiago (Zozô) Ozores"
license = '<a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.pt-br">CC BY-NC-SA-4.0</a>'
description = "Site Pessoal do Zozô"
keywords = "blog,personal,devops,sre,linux,opensource"
info = ["Staff Site Reliability Engineer", "Instrutor"]
#avatarURL = "images/courage.jpg"
gravatar = "tozores@gmail.com"
dateFormat = "January 2, 2006"
since = 2024
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/zozores/zozores-coder/tree/"
# Right To Left, shift content direction for languages such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
[params.goatCounter]
code = "zozores"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
# [params.cloudflare]
# token = "token"

# If you want to use Umami(https://umami.is) for analytics, add this section
[params.umami]
siteID = "5b8de95d-a003-44f0-805e-3b6925053a03"
scriptURL = "https://stats.zozor.es/script.js"

[params.utterances]
  repo = "zozores/zozores-coder" # https://utteranc.es/#heading-repository
  issueTerm = "title" # https://utteranc.es/#heading-mapping
  label = "[Blog]" # https://utteranc.es/#heading-issue-label
  theme = "github-dark" # https://utteranc.es/#heading-theme

[params.csp]
  childsrc = ["'self'"]
  fontsrc = [
    "'self'",
    "https://fonts.gstatic.com",
    "https://cdn.jsdelivr.net/"
  ]
  formaction = ["'self'"]
  framesrc = [ 
    "'self'",
    "https://utteranc.es"
  ]
  imgsrc = [
    "'self'",
    "https://zozores.goatcounter.com",
    "https://www.gravatar.com",
    "https://utteranc.es"
  ]
  objectsrc = ["'none'"]
  stylesrc = [
    "'self'",
    "'unsafe-inline'",
    "https://fonts.googleapis.com/",
    "https://cdn.jsdelivr.net/",
    "https://utteranc.es"
  ]
  scriptsrc = [
    "'self'",
    "'unsafe-inline'",
    "https://www.google-analytics.com",
    "https://stats.zozor.es",
    "https://zozores.goatcounter.com",
    "https://utteranc.es",
    "https://identity.netlify.com",
    "https://gc.zgo.at"
  ]
  # connect-src directive – defines valid targets for XMLHttpRequest (AJAX), WebSockets or EventSource
  connectsrc = [
    "'self'",
    "https://stats.zozor.es",
    "https://zozores.goatcounter.com",
    "https://utteranc.es"
  ]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "RSS"
icon = "fa-solid fa-rss fa-2x"
weight = 1
url = "https://zozor.es/index.xml"
rel = "alternate"
type = "application/rss+xml"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 2
url = "https://github.com/zozores/"

[[params.social]]
name = "Gitlab"
icon = "fa-brands fa-gitlab fa-2x"
weight = 3
url = "https://gitlab.com/zozores/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/tozores/"

[[params.social]]
name = "Mastodon"
icon = "fa-brands fa-mastodon fa-2x"
weight = 5
url = "https://bolha.us/@zozorest"

[[params.social]]
name = "Bluesky"
icon = "fa-brands fa-bluesky fa-2x"
weight = 6
url = "https://bsky.app/profile/zozores.bsky.social"

[[params.social]]
name = "Threads"
icon = "fa-brands fa-threads fa-2x"
weight = 7
url = "https://bsky.app/profile/zozores.bsky.social"

[[params.social]]
name = "dev.to"
icon = "fa-brands fa-dev fa-2x"
weight = 8
url = "https://dev.to/zozores"

[[params.social]]
name = "Hashnode"
icon = "fa-brands fa-hashnode fa-2x"
weight = 9
url = "https://hashnode.com/@zozores"

[[params.social]]
name = "Telegram"
icon = "fa-brands fa-telegram fa-2x"
weight = 10
url = "https://t.me/zozores"

[languages.en]
title = "~/zozores"
languageName = "EN"

[languages.en.params]
author = "Thiago (Zozô) Ozores"
license = '<a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en">CC BY-NC-SA-4.0</a>'
description = "Zozô's Personal Site"
keywords = "blog,personal,devops,sre,linux,opensource"
info = ["Staff Site Reliability Engineer", "Instructor"]

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "pages/about/"

[[languages.en.menu.main]]
name = "Posts"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Categories"
weight = 3
url = "categories/"

[[languages.en.menu.main]]
name = "Tags"
weight = 4
url = "tags/"

[languages.pt-br]
languageName = "PT"
title = "~/zozores"

[languages.pt-br.params]
author = "Thiago (Zozô) Ozores"
license = '<a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.pt-br">CC BY-NC-SA-4.0</a>'
description = "Site Pessoal do Zozô"
keywords = "blog,personal,devops,sre,linux,opensource"
info = ["Staff Site Reliability Engineer", "Instrutor"]

[[languages.pt-br.menu.main]]
name = "Sobre"
weight = 1
url = "pages/about/"

[[languages.pt-br.menu.main]]
name = "Postagens"
weight = 2
url = "posts/"

[[languages.pt-br.menu.main]]
name = "Categorias"
weight = 3
url = "categories/"

[[languages.pt-br.menu.main]]
name = "Tags"
weight = 4
url = "tags/"