[build]
publish = "public"
command = "hugo"

[build.environment]
HUGO_VERSION = "0.135.0"

[context.deploy-preview]
command = "hugo --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'https://giscus.app';"