[build]
publish = "public"
command = "hugo"

[build.environment]
HUGO_VERSION = "0.135.0"

[context.deploy-preview]
command = "hugo --buildFuture --buildDrafts --baseURL $DEPLOY_PRIME_URL"

[[redirects]]
from = "/blog/smag-1"
to = "/posts/analista-mestre-supremo-das-gal%C3%A1xias-1"
status = 301
force = true

# [[headers]]
#   for = "/*"
#   [headers.values]
#     Content-Security-Policy = "frame-ancestors 'none';"