backend:
  name: git-gateway

media_folder: "static/images"
public_folder: "/images"

i18n:
  structure: multiple_files
  locales: [pt-br, en]
  default_locale: pt-br

collections:
  - name: posts
    label: Posts
    folder: content/posts
    create: true
    i18n: true
    format: toml-frontmatter
    fields:
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Author", name: "author", widget: "string", required: true}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", required: true}
      - {label: "Categories", name: "categories", widget: "list", required: true}
      - {label: "Tags", name: "tags", widget: "list", required: true}
      - {label: "Series", name: "series", widget: "list", required: false}
      - {label: "Featured Image", name: "featuredImage", widget: "image", required: false}
      - {label: "External Link", name: "externalLink", widget: "string", required: false}
      - {label: "TOC", name: "toc", widget: "boolean", default: true}
      - {label: "Comments", name: "disableComments", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
